export const ACTIONS = Object.freeze({
  GET_GROUPS: 'GET_GROUPS',
  FETCH_CONTACTS: 'FETCH_CONTACTS',
  START_AUTOMATION: 'START_AUTOMATION',
  SEND_MESSAGE: 'SEND_MESSAGE',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  LOAD_SETTINGS: 'LOAD_SETTINGS',
  UPDATE_PROGRESS: 'UPDATE_PROGRESS',
  GET_PROGRESS: 'GET_PROGRESS',
  OPEN_DASHBOARD: 'OPEN_DASHBOARD',
  OPEN_CHAT: 'OPEN_CHAT',
  SCRAPE_GROUP: 'SCRAPE_GROUP',
  START_CAMPAIGN_FROM_STORAGE: 'START_CAMPAIGN_FROM_STORAGE',
  PAUSE_AUTOMATION: 'PAUSE_AUTOMATION',
  RESUME_AUTOMATION: 'RESUME_AUTOMATION',
  STOP_AUTOMATION: 'STOP_AUTOMATION',
  GET_CHAT_SNAPSHOT: 'GET_CHAT_SNAPSHOT',
  PING: 'PING'
});

export function getAction(message = {}) {
  return message.action || message.type || '';
}

export function createMessage(action, payload = {}) {
  return { action, ...payload };
}
